name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: cargo build
        run: |
          rustc --version --verbose
          cargo --version --verbose
          RUSTFLAGS="-D warnings" cargo build

      - name: cargo test
        run: cargo test --verbose

      - name: rustfmt
        run: |
          cargo fmt --version
          cargo fmt --all -- --check
      # See https://github.com/rust-lang/rust-clippy#travis-ci.
      # Right now we have way too many warnings to turn on -D warnings, but this
      # should be a goal in the future. We should also figure out a way to turn
      # on -D warnings on select modules.
      # - name: clippy
      #   run: |
      #     rustup component add clippy
      #     cargo clippy --version
      #     cargo clippy --all-targets --all-features # -- -D warnings
